/**
 * @author: Edson A. Terceros T.
 */

package com.umss.siiu.filestorage.model;

public enum FileTypeCategory {
    DIPLOMA_BACHILLER,
    TITULO_PROVISION_NACIONAL,
    DIPLOMA_ACADEMICO,
    TITULO_POSTGRADO,
    RR_HOMOLOGACION_DIPLOMA_BACHILLER,
    RR_HOMOLOGACION_DIPLOMA_POLICIA,
    RR_HOMOLOGACION_DIPLOMA_MILITAR,
    DOCUMENTO_VARIOS,
    IMAGEN_FIRMA;
}
